Sql no sql
Andryxa/mentoring pull request #5
Opened 2021-12-07 08:34 UTC by Andryxa

2021-12-10 14:03 UTC, ShuFFel commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +    private Statement statement;
эта штука должна быть у каждого метода своя

2021-12-10 14:03 UTC, ShuFFel commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +    private ResultSet resultSet;
эта штука должна быть у каждого метода своя

2021-12-10 14:04 UTC, ShuFFel commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +            statement = connection.createStatement();
стэйтмент надо создавать на каждый запрос к базе (бтв хз как оно работет в таком варианте)

2021-12-10 14:04 UTC, ShuFFel commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +            e.printStackTrace();
тут вроде как надо закрывать стейтмент

2021-12-10 14:05 UTC, ShuFFel commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +            while (resultSet.next()) {
этого тут быть не должно

2021-12-10 14:05 UTC, ShuFFel commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +            while (resultSet.next()) {
точнее тут не должно быть печати результатов

2021-12-10 14:05 UTC, ShuFFel commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +                System.out.printf("id: %d, name: %s ", id, name);
тоже самое, печатем не тут а в менюхах

2021-12-10 14:07 UTC, ShuFFel commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/NoSQLFunctionalImpl.java
> +    private MongoCollection<Document> collection;
зачем тебе тут коллекция если ты (что правильно) ходишь за ней при каждом вызове метода

2021-12-10 14:08 UTC, ShuFFel commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/NoSQLFunctionalImpl.java
> +        collection.find()
кросивое

2021-12-10 19:43 UTC, ShuFFel commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructor().newInstance();
Все эти строки надо надо вынести как параметры конструктора и передавать их в мейне

2021-12-13 06:53 UTC, AndrejKlim requested changes

2021-12-13 06:53 UTC, AndrejKlim commented on SQL_NoSQL/src/main/java/com/sql/Main.java
> +        final Scanner scanner = new Scanner(System.in);
Если ты уже начал пользоваться var, то в этих строках лучшее им применение

2021-12-13 06:53 UTC, AndrejKlim commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +            Class.forName("com.mysql.cj.jdbc.Driver").getDeclaredConstructor().newInstance();
Регистрация драйвера производится в самом драйвере. Из этого класса
`// // Register ourselves with the DriverManager // static { try { java.sql.DriverManager.registerDriver(new Driver()); } catch (SQLException E) { throw new RuntimeException("Can't register driver!"); } }`

2021-12-13 06:53 UTC, AndrejKlim commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +        } catch (InstantiationException | IllegalAccessException | InvocationTargetException | SQLException | ClassNotFoundException | NoSuchMethodException e) {
Если ты такую гору ошибок обрабатываешь одинаково, то можно поставить просто
`Exception e`
вместо перечисления всех

2021-12-13 06:53 UTC, AndrejKlim commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +            statement.executeUpdate(query);
На каждый метод нужно создавать стейтмент и закрывать его, например в блоке finally

2021-12-13 06:53 UTC, AndrejKlim commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +        String query = "select id, name from users where name = '" + surname + "';";
Как у тебя выглядит таблица? Если там только две этих колонки то можно и удобнее писать просто `select * from....`

2021-12-13 06:53 UTC, AndrejKlim commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +        String query = "select * from " + table;
Такой подход обычно не используют, а именно подставление таблицы к запросу. Чаще всего в одной таблице лежит один тип сущностей и к этой таблице создают DAO класс. Если у тебя в этом классе идет работа с таблицей users, то и работай только с ней

2021-12-13 06:53 UTC, AndrejKlim commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +        String query = "select id, name from books where using_by = 1;";
В таком тестовом проекте можно использовать цифры без объяснения, но обычно в таком случае создают Enum  со статусами.

2021-12-13 06:53 UTC, AndrejKlim commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +                System.out.printf("id: %d, name: %s ", id, name);
Как уже сказал @ShuFFel не делай вывод в методах DAO класса. Ты нарушаешь прицип единственной ответственности. При селекте собери данные в список и отдай дальше, и пусть там разбираются что делать с данными твоими. Например вывести их на консоль

2021-12-13 06:53 UTC, AndrejKlim commented on SQL_NoSQL/src/main/java/com/sql/menu/NoSQLMenu.java
> +                if (method == 1) {
Учитывая то что ты пишешь на 17 версии, можешь попробовать сюда прикрутить новый switch, будет более читаемо как по мне. Получится что-то похожее на:
`switch(method) {
  case 1 -> showAll();
  case -> addUser();
...
}`

2021-12-13 06:53 UTC, AndrejKlim commented on SQL_NoSQL/src/main/java/com/sql/Main.java
> +        } else if (selection == 2) {
else можно удалить по сути, будет 
`        if (selection == 1) {
            sqlMenu.start();
        }
         if (selection == 2) {`
Будет и читаться лучше и выглядеть

2021-12-13 06:53 UTC, AndrejKlim commented on SQL_NoSQL/src/main/java/com/sql/dao/Functional.java
> +public interface Functional {
Мне не нравится название этого интерфейса. Оно ничего не говорит о себе. Попробуй придумать что-то более понятное, может CommonMethods, DbFunctions, DbMethods что-то в этом духе

2021-12-13 06:53 UTC, AndrejKlim commented on SQL_NoSQL/src/main/java/com/sql/dao/impl/SQLFunctionalImpl.java
> +            connection = DriverManager.getConnection(url, username, password);
Пока у тебя нет пула соединений, создавай connection и statement в каждом запросе, и закрывай их в блоке finally. Или делай try-with-resources

2021-12-14 06:04 UTC, AndrejKlim requested changes

2021-12-14 06:04 UTC, AndrejKlim commented on SQL_NoSQL/src/main/java/com/sql/menu/NoSQLMenu.java
> +        for (int i = 0; i < search.size(); i++) {
Выдерживай какие-то стилистические рамки. В строках 67 и 72 ты делаешь то де самое но через list.forEach(). Либо  тут делай так же, либо в верхних строках так же как тут

2021-12-14 06:04 UTC, AndrejKlim commented on SQL_NoSQL/src/main/java/com/sql/menu/SQLMenu.java
> +        search.forEach(System.out::println);
Ну вот в дополнение к предывдущему комменту. Выше ты передавал в forEach лямбду `(s) -> System.out.println(s)` а теперь ссылку на метод `System.out::println`. Выбери пожалуйста что-то одно и сделай так

2021-12-14 07:12 UTC, merged