Spring
Andryxa/mentoring pull request #6
Opened 2022-01-05 15:12 UTC by Andryxa

2022-01-06 08:29 UTC, ShuFFel commented on Spring/src/main/java/ru/andryxa/spring/controllers/BooksController.java
> +        return "Book added";
обычно возвращают либо созданную модель, либо id созданной модели, делается это для того чтобы на фронт части сразу после запроса можно было адекватно отрисовать обновленный результат или хотя бы получить по уникальному идентификатору

2022-01-06 08:29 UTC, ShuFFel commented on Spring/src/main/java/ru/andryxa/spring/controllers/BooksController.java
> +        return "Updated!";
тоже странный результат, лучше вернуть опять же, либо обновленную модель либо ее идентификатор

2022-01-06 08:29 UTC, ShuFFel commented on Spring/src/main/java/ru/andryxa/spring/controllers/SubscriptionsController.java
> +        return "Add new subscription";
id или модель

2022-01-06 08:29 UTC, ShuFFel commented on Spring/src/main/java/ru/andryxa/spring/controllers/SubscriptionsController.java
> +        return "Update done!";
id или модель

2022-01-06 08:29 UTC, ShuFFel commented on Spring/src/main/java/ru/andryxa/spring/controllers/UsersController.java
> +        return "add new user";
id или модель

2022-01-06 08:29 UTC, ShuFFel commented on Spring/src/main/java/ru/andryxa/spring/controllers/UsersController.java
> +        return "Updated!!!";
id или модель

2022-01-10 11:07 UTC, AndrejKlim requested changes

2022-01-10 11:07 UTC, AndrejKlim commented on Spring/src/main/java/ru/andryxa/spring/controllers/BooksController.java
> +    public BookDTO newBook(@RequestParam("name") String name,
Поменяй сборку ДТО из нескольких объектов получаемых из параметров запроса в получение объекта целиком из тела запроса. Будет примерно так
```suggestion
    public BookDTO newBook(@RequestParam BookDTO book) {
```

2022-01-10 11:07 UTC, AndrejKlim commented on Spring/src/main/java/ru/andryxa/spring/controllers/BooksController.java
> +    @PostMapping("/updateBook")
```suggestion
    @PutMapping("/updateBook")
```

2022-01-10 11:07 UTC, AndrejKlim commented on Spring/src/main/java/ru/andryxa/spring/service/BookService.java
> +    public BookDTO getBookDTO(Book book) {
Такие методы по преобразованию объектов друг в друга можно вынести в классы-мапперы со статическими методами. Например class BookMapper

2022-01-10 11:07 UTC, AndrejKlim commented on Spring/src/main/java/ru/andryxa/spring/service/BookService.java
> +    public List<BookDTO> getListOfBooks() {
По желанию можешь изучить Stream Api и применить сюда. Получится что-то вроде
`return bookRepo.findAll().stream().map(this::getBookDTO).collect(Collectors.toList())`
или если учитывать твою версию Java то:
`return bookRepo.findAll().stream().map(this::getBookDTO).toList()`

2022-01-10 11:07 UTC, AndrejKlim commented on Spring/src/main/java/ru/andryxa/spring/service/BookService.java
> +    @Autowired
если поле `private final`, то `@Autowired` не нужен

2022-01-10 11:45 UTC, ShuFFel commented on Spring/src/main/java/ru/andryxa/spring/service/BookService.java
> +    @Autowired
не нужен - слишком громко сказано, хоть тут @Autowired не обязателен, он никому тут не мешает, а на будущее в случае с большими сервисам с большим количествном полей, лучче прописавть аннотации явно чтобы следующий разработчик сразу видел что где и куда линкуется

2022-01-12 15:25 UTC, ShuFFel commented on Spring/src/main/java/ru/andryxa/spring/mappers/BookMapper.java
> +    public BookMapper() {
приватный конструктора в таких штуках приветствуется

2022-01-12 15:25 UTC, ShuFFel commented on Spring/src/main/java/ru/andryxa/spring/mappers/SubscriptionMapper.java
> +
приватный конструктор

2022-01-14 06:30 UTC, AndrejKlim requested changes

2022-01-14 06:30 UTC, AndrejKlim commented on Spring/src/main/java/ru/andryxa/spring/controllers/BooksController.java
> +    private BookService bookService;
Что-то мне подказывает, что это не  будет работать без подставления этой зависимости.

2022-01-14 06:30 UTC, AndrejKlim commented on Spring/src/main/java/ru/andryxa/spring/mappers/BookMapper.java
> +    public static BookDTO getBookDTO(Book book) {
Не совсем понятные имена методов. Ты не получаешь объект (get...) ты его преобразуешь (map... transform... etc)

2022-01-14 06:30 UTC, AndrejKlim commented on Spring/src/main/java/ru/andryxa/spring/service/impl/BookServiceImpl.java
> +        book.setName(bookDTO.getName());
Эту модификацию объекта тоже можешь вынести в маппер

2022-01-14 06:30 UTC, AndrejKlim commented on Spring/src/main/java/ru/andryxa/spring/service/impl/BookServiceImpl.java
> +        return BookMapper.getBookDTO(bookRepo.save(book));
orElseThrow() не кажется оправданным. Почему ты решил сделать так?
Если вынести изменение объекта в маппер то итоговый код может выглядеть так
`return bookRepo.findById(bookDTO.getId())
.map(BookMapper::updateEntity)
.map(BookMapper.getBookDTO(bookRepo.save(book))
.orElse(null);`

2022-01-25 15:17 UTC, merged